name: speedcode_flutter
description: emad h basri

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_statusbarcolor: ^0.2.3
  flutter_swiper: ^1.1.6
  provider: ^5.0.0
  flutter_spinkit: ^4.1.2+1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/foodApp1/
    - assets/images/foodApp2/
    - assets/images/LoginSignUpAnimation/
    - assets/images/NikeShop/
    - assets/images/UiItems/
