name: speedcode
description: emad h basri

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_statusbarcolor: ^0.2.3
#  provider: ^5.0.0
#  get_it: ^3.0.3
#  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/foodApp1/
#    - assets/images/RestaurantFullAnimationApp1/